apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.externalSecretName }}
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.global.externalSecretName }}
  data:
    {{- range .Values.global.externalSecret }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}