apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.global.secretStore.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.global.secretStore.url | quote }}
      path: {{ .Values.global.secretStore.path | quote }}
      version: {{ .Values.global.secretStore.kvVersion | quote }}
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.global.secretStore.role | quote }}
          serviceAccountRef:
            name: {{ .Values.global.saName | quote }}